### PR TITLE
Add mpq to client list

### PR DESCRIPTION
**Pull request by codesoap**

### CODE REVIEW

**Comment by MaxKellermann** [comment]
A "minimal" client?
```
   text	   data	    bss	    dec	    hex	filename
2918765	 122244	 211200	3252209	 319ff1	mpq
 228442	  13760	   2993	 245195	  3bdcb	output/release/ncmpc
  79076	   4872	   1640	  85588	  14e54	output/mini/ncmpc
```
That "minimal client" is more than twelve times larger than a fully-featured ncmpc!
And it's more than 36 times larger than a ncmpc build with all optional features disabled, which still has many more features than mpq.
WTF, man!

**Comment by MaxKellermann** [comment]
Plus, mpq allocates 1.5 GB (!!!) RAM at startup, and creates 13 threads. While a fully-featured ncmpc allocates just 12 MB and runs in a single thread.

**Comment by codesoap** [comment]
> That "minimal client" is more than twelve times larger than a fully-featured ncmpc!
When calling mpq minimal, I was referring to it's user interface (just 11 commands) and amount of code (under 600 SLOC), not to it's binary size. mpq is written in go and the go compiler does indeed produce significantly larger binaries than gcc or clang. The mpq binary for Linux (amd64) is ca. 4.1MiB in size; I feel like this will not be an issue for most users.

> ncmpc [...] which still has many more features than mpq.
My major motivation for writing mpq was to reduce features to an absolute minimum, because I always forgot how to use the more fully featured mpd clients. Thus I don't see this as valid criticism.

> Plus, mpq allocates 1.5 GB (!!!) RAM at startup
Could you tell me how you found this number? When I run `/usr/bin/time -l mpq` (using the OpenBSD [time(1)](https://man.openbsd.org/time.1), I get something like `6268  maximum resident set size` (ca. 6.1MiB).

> and creates 13 threads
I don't see an issue with a program creating some threads. What problem do you see here?

**Comment by MaxKellermann** [comment]
> My major motivation for writing mpq was to reduce features to an absolute minimum, because I always forgot how to use the more fully featured mpd clients. Thus I don't see this as valid criticism.

Your opinion is valid, but so is my criticism. Of course you can write any software with any amount you want, and I can criticize that any amount I want.
Your disagreement with me is not "bloat is never bad", it is only "this amount of bloat is not an issue for most users", which is much weaker, and doesn't even disagree with me.

> > Plus, mpq allocates 1.5 GB (!!!) RAM at startup
> 
> Could you tell me how you found this number? When I run `/usr/bin/time -l mpq` (using the OpenBSD [time(1)](https://man.openbsd.org/time.1)), I get something like `6268 maximum resident set size` (ca. 6.1MiB).

I counted how much memory was allocated, not how much was resident (i.e. faulted). This is `ps` output:
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
max      3669216  0.5  0.0 1595056 10684 pts/11  Sl+  19:25   0:00  |   |   \_ ./mpq
max      3669279  2.0  0.0  12800  7144 pts/40   S+   19:25   0:00  |       \_ ncmpc
```

This is with a 16k queue:
```
max      3669358  4.8  0.0 1817276 29936 pts/11  Sl+  19:29   0:00  |   |   \_ ./mpq
max      3669465  1.3  0.0  19440 16744 pts/40   S+   19:29   0:00  |   |   \_ ./output/mini/ncmpc
```
Plus 19 MB in mpq, plus 9 MB for ncmpc. For the few features mpq has, it's very inefficient. (It also uses twice as much CPU.)

> > and creates 13 threads
> 
> I don't see an issue with a program creating some threads. What problem do you see here?

Excessive bloat which serves no use at all. mpq does nothing better than ncmpc, but still uses much more resources; it would be easy to make more of ncmpc's features optional and strip them out, if the goal was to make a client more minimalistic than ncmpc.

Deciding whether this amount of bloat is a "problem" or not is a matter of taste. Most contemporary software is much more bloated than the predecessor it replaced. Sometimes that bloat comes with more features, but in this case, it comes with less features.

The problem isn't one single bloated program. The problem is "what if everybody does it?" - it's like driving a huge SUV and thinking that one car won't cause global warming. That's not wrong, but only part of the story.
The problem is when all programs use excessive amounts of memory and threads. A few megabytes here, a few megabytes there, and suddenly you need gigabytes of RAM for a desktop environment, which is ridiculous.

**Comment by codesoap** [comment]
Thank you for merging and addressing my objections. It seems to me like we are shifting into a more philosophic realm and you are mostly comparing C to Go now, but I don't want to excercise a war of programming languages here.

Let me just say that I think a balance between readability and bloat must be found and I seem to value readability higher than you and/or find Go code more readable than C code.

> Your disagreement with me is not "bloat is never bad", it is only "this amount of bloat is not an issue for most users", which is much weaker, and doesn't even disagree with me.

Point taken. I do indeed dislike bloat, but will tolerate it to some degree, if I receive other benefits in exchange. I would assume the same—although to a lesser degree—is true for you, since you didn't make an argument for assembler.

> This is ps output: [...] This is with a 16k queue:

Thanks for the insight. Seeing these numbers made me realize I was wasting a bit of memory by storing some unused details of songs. I fixed this in https://github.com/codesoap/mpq/commit/7d82c54ff705eff7691e08669a26894ee389a294. There seems to be less of a difference in memory usage now, when the queue is long.

**Pull request merged**
