### PR TITLE
MMC4W v2.0.0 Released

### PR DESCRIPTION
**Pull request by drgerg**
v2.0.0 of the Minimal MPD Client For Windows is now available at https://github.com/drgerg/mmc4w .

### CODE REVIEW

**Comment by drgerg** [comment]
I believe I formatted things properly.  If I did something incorrectly, please let me know.
Thanks!

**Comment by MaxKellermann** [comment]
Bad commit message

**Comment by MaxKellermann** [comment]
`git commit --amend` and delete the first line of the commit message - because what does "2024-02-21-mmc4w-2-dot-0-dot-0-released" mean?

**Comment by MaxKellermann** [comment]
It's not about the PR comment, it's about the commit message. I told you how to fix this but you did something else.

**Comment by drgerg** [comment]
OK.  My bad.  I'll try to follow your instructions more closely.
Sorry for wasting your time.

**Comment by drgerg** [comment]
I think I know too little about using git to be doing this.  I want to back out of this one and see if I can read enough resources to learn how to do it from the command line using git instead of the web interface on Github.
Thank you for your effort in attempting to direct me.  This is a good learning experience.

**Pull request closed without merging**
