### PR TITLE
updated mpdevil's description

### PR DESCRIPTION
**Pull request by SoongNoonien**

### CODE REVIEW

**Comment by MaxKellermann** [comment]
The new description looks worse - it removes information and replaces it with some text devoid of information. Your commit message doesn't explain anything.

**Comment by SoongNoonien** [comment]
> Your commit message doesn't explain anything.

I don't see what could be missing. I simply updated the description to match the new description used by my project anywhere else. Isn't that what the description on the website of mpd should be?

**Comment by SoongNoonien** [comment]
> An explanation of why you believe the information previously present on the MPD website should be removed.

I get the feeling that there is no explanation that could convince you. ;-)

> If the description on a project website is bad, the MPD website should not echo that. In this case, the description on your website is bad, because it is devoid of information, it is generic blah-blah. It is worse than the old text.

If you don't want to change it, it's fine with me, it's your website after all. But keep in mind that the current description does not reflect the intentions of the developer whose software you are promoting.

**Comment by MaxKellermann** [comment]
> I get the feeling that there is no explanation that could convince you. ;-)

You didn't even try.

> If you don't want to change it, it's fine with me, it's your website after all. But keep in mind that the current description does not reflect the intentions of the developer whose software you are promoting.

Fact check:
- your own commit in this repository adding the description "small GTK+ MPD client written in python" https://github.com/MusicPlayerDaemon/website/commit/63a06fd477ec252c9042a58d932ccd4d163710c6 (note the bad commit message!)
- your own commit 12 hours later updating your project's description: https://github.com/SoongNoonien/mpdevil/commit/486865963fcf83cad9fe8268d598f64527e3f690 (also bad commit message!)
- this new description has (mostly) not changed in the last 2 years; no new intention is being reflected here since you added your project description to the MPD website
- your new description "simple music browser for MPD" (https://github.com/MusicPlayerDaemon/website/pull/66/commits/4c76fa1ddf235cd08a6dae6ead87874b0f321e60 with another bad commit message) matches neither the old one nor the new one from your README

I don't see how your proposed website change reflects the intentions documented on your own project's git repository. The change takes away useful information, for no reason at all. It doesn't add anything, and doesn't remove anything that is incorrect. Your client is still "small" and "GTK+" and "MPD client" and "python".
Yeah, it's a "music browser", but that's generic blah blah because (almost) every interactive MPD client is a music browser. That's not an interesting piece of information.

Yes, it's my website, and I want it to be informative. You want the website to be less informative, and I reject that.

**Comment by SoongNoonien** [comment]
> your own commit in this repository adding the description "small GTK+ MPD client written in python" https://github.com/MusicPlayerDaemon/website/commit/63a06fd477ec252c9042a58d932ccd4d163710c6 (note the bad commit message!)

I'm not sure what you want to tell me with that. The commit message seems to have fulfilled your criteria as you merged it.

> your own commit 12 hours later updating your project's description: https://github.com/SoongNoonien/mpdevil/commit/486865963fcf83cad9fe8268d598f64527e3f690 (also bad commit message!)

I changed the detailed description in the README not the short description. The short description in the README was a placeholder for an actual detailed description. The commit message is in _my_ repository and is good enough for me.

> your new description "simple music browser for MPD" (https://github.com/MusicPlayerDaemon/website/commit/4c76fa1ddf235cd08a6dae6ead87874b0f321e60 with another bad commit message) matches neither the old one nor the new one from your README

You are obviously confusing detailed descriptions with short descriptions. It is clear that putting the complete README text on your website never was intended. I simply want to sync the short description (or claim if you like) across the various references of mpdevil (e.g. its github repository, its about dialog, PKGBUILD's, ebuild's,...).

> I don't see how your proposed website change reflects the intentions documented on your own project's git repository.

It reflects, as I already stated before, the new short description of mpdevil which is also part of the git repository.

> The change takes away useful information, for no reason at all. It doesn't add anything, and doesn't remove anything that is incorrect. Your client is still "small" and "GTK+" and "MPD client" and "python".
Yeah, it's a "music browser", but that's generic blah blah because (almost) every interactive MPD client is a music browser. That's not an interesting piece of information.

This would all be part of a general discussion about the new short description but not of the discussion about this merge request.

> You want the website to be less informative, and I reject that.

This is untrue and I think I made clear what my intends are.

**Pull request closed without merging**
