### PR TITLE
MMC4W v2.0.1 Released

### PR DESCRIPTION
**Pull request by drgerg**
MMC4W The Minimal MPD Client for Windows [v2.0.1](https://github.com/drgerg/mmc4w/tree/main) is now available.

A new Queue menu lists the queue so you can search for and jump to specific songs in the current queue.

Folder art is now supported in addition to embedded art.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
What's that second commit? It has a bad commit message and contains a fixup for a known-bad commit in the same PR.

**Comment by MaxKellermann** [comment]
Closed? You don't want to submit this change after all?
(Do NOT create a new PR.)

**Comment by drgerg** [comment]
Obviously I still don't know what I'm doing here in Github.  I have a lot of questions but nowhere to ask them.  
Thanks for your patience.

**Comment by MaxKellermann** [comment]
I don't understand your question. What does it mean to "close" a GitHub fork? And why should I care on which one of your computers you clone it then? Even GitHub doesn't know which computers you use. Your question does not appear to make any sense.

**Comment by MaxKellermann** [comment]
> then clone it on my Mint laptop from your 'website' repo, would you see my commits?

No, because I have no access to your Mint laptop. How, in your imagination, would it technically be possible for me to see files that are only on your computer?

**Comment by drgerg** [comment]
That answers my question.  

So now how do I fix my error here in this pull request?  I do not have a clue at this point.

**Comment by MaxKellermann** [comment]
I said it already: amend the bad commit, force-push to GitHub.

**Comment by drgerg** [comment]
I believe I followed your instructions.  The root of my confusion is I really don't know what a "good" commit message looks like.  I am coming to the conclusion that it needs to be more informative to you about what the commit changes rather than just a title.

I intend to learn and get better at this stuff.  Thanks for your help.

**Comment by MaxKellermann** [comment]
No, you didn't. You did not amend the bad commit. Instead, you amended the commit message of the fixup commit.

**Comment by drgerg** [comment]
OK.  I'm not able to find a way to edit the commit message for a commit that is not the most recent.  I guess you can just ignore this pull request.

**Comment by drgerg** [comment]
I sure hope this has achieved the desired result.

**Pull request merged**
